export const activities = [
  {
    activityType: "bike",
    weather: "placeholder",
    duration: "placeholder",
    distance: "placeholder",
    comment: "placeholder",
    date: "placeholder",
  },
  {
    activityType: "bike",
    weather: "placeholder",
    duration: "placeholder",
    distance: "placeholder",
    comment: "placeholder",
    date: "placeholder",
  },
  {
    activityType: "bike",
    weather: "placeholder",
    duration: "placeholder",
    distance: "placeholder",
    comment: "placeholder",
    date: "placeholder",
  },
  {
    activityType: "bike",
    weather: "placeholder",
    duration: "placeholder",
    distance: "placeholder",
    comment: "placeholder",
    date: "placeholder",
  },
  {
    activityType: "bike",
    weather: "placeholder",
    duration: "placeholder",
    distance: "placeholder",
    comment: "placeholder",
    date: "placeholder",
  },
  {
    activityType: "bike",
    weather: "placeholder",
    duration: "placeholder",
    distance: "placeholder",
    comment: "placeholder",
    date: "placeholder",
  },
  {
    activityType: "bike",
    weather: "placeholder",
    duration: "placeholder",
    distance: "placeholder",
    comment: "placeholder",
    date: "placeholder",
  },
  {
    activityType: "bike",
    weather: "placeholder",
    duration: "placeholder",
    distance: "placeholder",
    comment: "placeholder",
    date: "placeholder",
  },
];
