export const activities = [
  {
    activityType: "bike",
    weather: "../icons/clear-day.svg",
    weatherCode: 1,
    temperature: "22°C",
    duration: "1h 45m",
    distance: "28.5",
    comment: "Perfect morning ride along the coast",
    date: "05-08-2025",
    location: "Bergen Coastal Route",
  },

  {
    activityType: "run",
    weather: "../icons/partly-cloudy-day.svg",
    weatherCode: 2,
    temperature: "18°C",
    duration: "42m",
    distance: "7.2",
    comment: "Great tempo run through the park",
    date: "04-08-2025",
    location: "Fløyen Trail",
  },
  {
    activityType: "hike",
    weather: "../icons/overcast.svg",
    weatherCode: 3,
    temperature: "15°C",
    duration: "3h 20m",
    distance: "12.8",
    comment: "Challenging hike with amazing views at the summit",
    date: "03-08-2025",
    location: "Mount Ulriken",
  },
  {
    activityType: "bike",
    weather: "../icons/rain.svg",
    weatherCode: 61,
    temperature: "16°C",
    duration: "1h 15m",
    distance: "18.3",
    comment: "Got caught in the rain but still enjoyed it",
    date: "02-08-2025",
    location: "City Center Loop",
  },
  {
    activityType: "run",
    weather: "../icons/clear-day.svg",
    weatherCode: 0,
    temperature: "20°C",
    duration: "35m",
    distance: "5.8",
    comment: "Easy recovery run on a beautiful sunny day",
    date: "01-08-2025",
    location: "Bryggen Waterfront",
  },
  {
    activityType: "hike",
    weather: "../icons/partly-cloudy-day.svg",
    weatherCode: 2,
    temperature: "17°C",
    duration: "2h 30m",
    distance: "9.4",
    comment: "Family hike to the lake, kids loved it",
    date: "31-07-2025",
    location: "Skomakerdiket Trail",
  },
  {
    activityType: "bike",
    weather: "../icons/drizzle.svg",
    weatherCode: 51,
    temperature: "14°C",
    duration: "2h 10m",
    distance: "32.1",
    comment: "Long ride in light drizzle, felt refreshing",
    date: "30-07-2025",
    location: "Hardangerfjord Route",
  },
];
